server:
  port: 8889
spring:
  config:
    activate:
      on-profile: test
  cloud:
    config:
      enabled: true
    bus:
      enabled: true
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
eureka:
    instance:
      prefer-ip-address: true
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        defaultZone: http://localhost:8761/eureka/
logging:
  level:
    org.springframework.security: DEBUG
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"
