server:
  port: 8889
spring:
  security:
    oauth2:
      client:
        registration:
          authentication-server:
            client-id: "${CLIENT_ID}"
            client-secret: "${CLIENT_SECRET}"
            scope: USER_MANAGEMENT_SERVER
            authorization-grant-type: client_credentials
        provider:
          authentication-server:
            token-uri: "${TOKEN_URI:http://localhost:9000/oauth2/token}"
      resourceserver:
        jwt:
          jwk-set-uri: "${JWK_SET_URI:http://localhost:9000/oauth2/jwks}"
  config:
    activate:
      on-profile: test
  cloud:
    config:
      enabled: true
    bus:
      enabled: true
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
eureka:
    instance:
      prefer-ip-address: true
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        defaultZone: http://localhost:8761/eureka/
logging:
  level:
    org.springframework.security: DEBUG
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"
