server:
  port: 8083
spring:
  config:
    activate:
      on-profile: qa
  data:
    redis:
      host: redis
      port: 6379
  cache:
    type: redis
  rabbitmq:
    host: rabbit
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true
redis:
  location: http://redis:6379
authserver:
  location: http://freelance-authserver:9000
client:
  location: http://localhost:8080
