server:
  port: 8761
spring:
  application:
    name: eurekaserver
  config:
    activate:
      on-profile: qa
eureka:
  instance:
    hostname: eurekaserver
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
