server:
  port: 9000
spring:
  config:
    activate:
      on-profile: qa
  application:
    name: freelance-authserver
  cloud:
    config:
      enabled: true
    bus:
      enabled: true
  datasource:
    url: "jdbc:mysql://${DATABASE_HOST:auth-db}:${DATABASE_PORT:3307}/${DATABASE_NAME:freelance-auth}"
    username: root
    password: root
  jpa:
    show-sql: true
  rabbitmq:
    host: rabbit
    port: 5672
    username: guest
    password: guest

management:
  health:
    rabbit:
      enabled: true
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  info:
    env:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: "*"
info:
  app:
    name: freelance-authserver
    description: "Freelance Auth Server"
    version: "1.0.0"
app:
  version: "1.0"

logging:
  level:
    org.springframework.security: DEBUG
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"