server:
  port: 9000
spring:
  config:
    activate:
      on-profile: test
  application:
    name: freelance-authserver
  cloud:
    config:
      enabled: true
    bus:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  security:
    oauth2:
      client:
        registration:
          freelance-authserver:
            client-id: "${CLIENT_ID}"
            client-secret: "${CLIENT_SECRET}"
            scope: USER_MANAGEMENT_SERVER
            authorization-grant-type: client_credentials
        provider:
          freelance-authserver:
            token-uri: "${TOKEN_URI:http://localhost:9000/oauth2/token}"
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
        defaultZone: http://localhost:8761/eureka/

management:
  health:
    rabbit:
      enabled: true
  info:
    env:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: "*"
info:
  app:
    name: freelance-authserver
    description: "Freelance Auth Server"
    version: "1.0.0"
app:
  version: "1.0"

logging:
  level:
    org.springframework.security: DEBUG
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"