server:
  port: 8072

spring:
  config:
    activate:
      on-profile: qa
    application:
      name: gatewayserver
  main:
    web-application-type: reactive
  cloud:
    config:
      enabled: true
    bus:
      enabled: true
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
  rabbitmq:
    host: rabbit
    port: 5672
    username: guest
    password: guest
  data:
    redis:
      host: redis
      port: 6379
  cache:
    type: redis

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/